# Generated by Django 6.1.1 on 2026-09-16 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_driverprofile_confirmed_at_driverprofile_driver_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('tech_inspection_expiry', models.DateField(blank=True, help_text='Mandatory inspection HU/AU (TÜV)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_ref', models.CharField(blank=True, help_text='Внешний ID для аналитики, формат VH-####', max_length=32, null=True, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=32)),
                ('gross_vehicle_weight_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payload_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('pallet_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], default='diesel', max_length=20)),
                ('euro_emission_class', models.CharField(default='Euro_6', help_text='Для German LKW-Maut', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test', models.BooleanField(default=False)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='users.driverprofile')),
                ('carrier', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pallet_capacity__gte', 0)), name='chk_vehicle_pallet_non_negative')],
            },
        ),
    ]
