# Generated by Django 6.1.1 on 2026-09-16 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('users', '0008_carriercompanyprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='carrier',
            field=models.ForeignKey(limit_choices_to={'role': 'carrier_company'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('gross_vehicle_weight_kg__gt', 0)), name='chk_vehicle_gvw_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('payload_capacity_kg__gt', 0)), name='chk_vehicle_payload_positive'),
        ),
    ]
