# Generated by Django 6.1.1 on 2026-09-15 09:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('users', '0003_alter_clientcompanyprofile_edrpou'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='euro_emission_class',
            field=models.CharField(default='Euro_6', help_text='Для German LKW-Maut', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], default='diesel', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_vehicle_weight_kg',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pallet_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='payload_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_ref',
            field=models.CharField(blank=True, help_text='Внешний ID для аналитики, формат VH-####', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tech_inspection_expiry',
            field=models.DateField(blank=True, help_text='Mandatory inspection HU/AU (TÜV)', null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('gross_vehicle_weight_kg__gt', 0), ('gross_vehicle_weight_kg__isnull', True), _connector='OR'), name='chk_vehicle_gvw_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('payload_capacity_kg__gt', 0), ('payload_capacity_kg__isnull', True), _connector='OR'), name='chk_vehicle_payload_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('pallet_capacity__gte', 0)), name='chk_vehicle_pallet_non_negative'),
        ),
    ]
