# Generated by Django 6.1.1 on 2026-09-15 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_euro_emission_class_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gross_vehicle_weight_kg',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='payload_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
