# Generated by Django 6.1.1 on 2026-09-17 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='payload_capacity_kg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
