# Generated by Django 6.1.1 on 2026-09-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='also_drives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_carrier_company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_drivers', to='users.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_photo',
            field=models.FileField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
