# Generated by Django 6.1.1 on 2026-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile_also_drives_driverprofile_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompanyprofile',
            name='edrpou',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
