# Generated by Django 6.1.1 on 2026-09-15 13:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('users', '0003_alter_clientcompanyprofile_edrpou'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='adr_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='avg_customer_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='base_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='code_95_categories',
            field=models.CharField(blank=True, help_text='EU Code 95 (BKrFQG)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='code_95_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 15, 13, 49, 58, 626779, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_drivers', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_ref',
            field=models.CharField(blank=True, help_text='Внешний ID для аналитики, формат DR-####', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driving_license_categories',
            field=models.CharField(blank=True, help_text='B, BE, C1, C1E, C, CE', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='has_adr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='service_compliance_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_reviews_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('avg_customer_rating__gte', 1.0), ('avg_customer_rating__lte', 5.0)), name='chk_driver_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('total_reviews_count__gte', 0)), name='chk_driver_reviews_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('service_compliance_rate__gte', 0.0), ('service_compliance_rate__lte', 100.0)), name='chk_driver_compliance_range'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code_95_categories__isnull', True), ('code_95_expiry_date__isnull', True)), models.Q(('code_95_categories__isnull', False), ('code_95_expiry_date__isnull', False)), _connector='OR'), name='chk_driver_code95_consistency'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('has_adr', False), ('adr_expiry_date__isnull', True)), models.Q(('has_adr', True), ('adr_expiry_date__isnull', False)), _connector='OR'), name='chk_driver_adr_consistency'),
        ),
    ]
