# Generated by Django 6.1.1 on 2026-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('users', '0004_driverprofile_adr_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompanyprofile',
            name='edrpou',
        ),
        migrations.AddField(
            model_name='clientcompanyprofile',
            name='company_registration_number',
            field=models.CharField(default=2, help_text='EUID або національний реєстраційний номер компанії (напр. HRB для Німеччини)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='EUID або національний реєстраційний номер компанії (напр. HRB для Німеччини)', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client_company', 'Замовник — фірма'), ('client_individual', 'Замовник — фізична особа'), ('driver', 'Водій / перевізник'), ('carrier_company', 'Перевізник — компанія'), ('accountant', 'Бухгалтер'), ('admin', 'Адміністратор системи')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_carrier_company', False), models.Q(('is_carrier_company', True), models.Q(('company_name', ''), _negated=True)), _connector='OR'), name='chk_carrier_company_has_name'),
        ),
    ]
