# Generated by Django 6.1.1 on 2026-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_clientcompanyprofile_edrpou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('self_employed', 'Sole Proprietorship (Gewerbe / Solo-Selbstständige)'), ('company_employee', 'Fleet Company Staff Driver')], help_text='Автоматично визначається на основі is_carrier_company/employer, якщо не вказано явно', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_confirmed_by_employer',
            field=models.BooleanField(default=False, help_text='Підтверджено керівником компанії-перевізника як штатний водій'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Free to Accept Orders'), ('on_trip', 'On Duty / Executing Delivery'), ('off_duty', 'Rest Period / Mandatory Break'), ('inactive', 'Account Blocked or Suspended')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
