# Generated by Django 6.1.1 on 2026-09-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverprofile_confirmed_at_driverprofile_driver_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_info',
        ),
    ]
