# Generated by Django 6.1.1 on 2026-09-16 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_driverprofile_vehicle_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(max_length=50, unique=True)),
                ('base_city', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='driverprofile',
            name='chk_carrier_company_has_name',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('self_employed', 'Sole Proprietorship (Gewerbe / Solo-Selbstständige)'), ('company_employee', 'Fleet Company Staff Driver')], help_text='Автоматично визначається на основі employer, якщо не вказано явно', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_confirmed_by_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carriercompanyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_drivers', to='users.carriercompanyprofile'),
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='also_drives',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='company_registration_number',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_carrier_company',
        ),
    ]
