# Generated by Django 6.1.1 on 2026-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_blocked_at_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client_company', 'Client — Company'), ('client_individual', 'Client — Individual'), ('driver', 'Driver / Carrier'), ('carrier_company', 'Carrier — Company'), ('accountant', 'Accountant'), ('admin', 'System Administrator')], max_length=20),
        ),
    ]
